=== HerbertV/JAppDater/data/jappdater/jappdater.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2005 rel. 3 U (http://www.altova.com) by Herbert Veitengruber (privat) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="JAppDater">
		<xs:annotation>
			<xs:documentation>update index for JAppDater. latest Version available here: http://xsd.veitengruber.com/jappdater.xsd</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="application">
					<xs:annotation>
						<xs:documentation>name = name of your application
version = the version of your application
server = contains sever and base path for all other references
index = the relative path to the server url</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:attribute name="name" type="xs:string" use="required"/>
						<xs:attribute name="version" type="xs:string" use="required"/>
						<xs:attribute name="server" type="xs:string" use="required"/>
						<xs:attribute name="index" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="files">
					<xs:annotation>
						<xs:documentation>files that are updated</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="file" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>src = relative path to the remote file
dest = destination folder relative to your application folder
version = (optional) version of this file
checksum = (optional) checksum of this file
unpack = (optional) if true and the source is a zip/jar the content is unpacked into dest folder
</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:attribute name="ID" type="xs:string" use="required"/>
									<xs:attribute name="src" type="xs:string" use="required"/>
									<xs:attribute name="dest" type="xs:string" use="required"/>
									<xs:attribute name="version" type="xs:string" use="optional"/>
									<xs:attribute name="checksum" type="xs:string" use="optional"/>
									<xs:attribute name="unpack" type="xs:boolean" use="optional"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="obsolete" minOccurs="0">
					<xs:annotation>
						<xs:documentation>List of files that are no longer needed.</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="file" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="ID" type="xs:string" use="required"/>
									<xs:attribute name="dest" type="xs:string" use="required"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="version" type="xs:string" use="required" fixed="1.1.0"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== HerbertV/JAppDater/data/jappdater/localsample.xml
<?xml version="1.0" encoding="UTF-8"?>
<JAppDater 
		version="1.1.0" 
		xsi:noNamespaceSchemaLocation="http://xsd.veitengruber.com/jappdater.xsd" 
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	>
	<!-- the index can also be a php file that generates a JAppDater xml -->
	<application 
			server="http://localhost:8080/herbertv/JAppDaterTest/"
			index="index.xml"
			name="SampleApp" 
			version="1.0"
		/>
	
	<files>
		<!-- updates always -->
		<file ID="1"
				src="sampleupdate/sample.txt" 
				dest="/sample.txt" 
			/>
		<!-- no update needed test -->
		<file  ID="2"
				src="sampleupdate/sample1.txt" 
				dest="/sample1.txt"
				version="1.0" 
			/>	
		<!-- update check with version number checksum works similiar -->
		<file  ID="3"
				src="sampleupdate/sample2.txt" 
				dest="subfolder/sample2.txt"
				version="1.0" 
			/>
		<!-- update sample with unpack -->
		<file  ID="4"
				src="sampleupdate/sample3.zip" 
				dest="unpackfolder/"
				version="1.0"
				unpack="true" 
			/>	
		<!-- this sample is removed -->
		<file  ID="5"
				src="sampleupdate/sampleObsolete.txt" 
				dest="/sampleObsolete.txt"
				version="1.0"
			/>		
	</files>
</JAppDater>
